# Generated by Django 3.2.8 on 2023-01-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=11)),
                ('date', models.DateField(null=True)),
                ('max_temp', models.IntegerField(null=True)),
                ('min_temp', models.IntegerField(null=True)),
                ('amount_precipitation', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('station', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('station', models.CharField(max_length=11)),
                ('avg_max_temp', models.IntegerField(null=True)),
                ('avg_min_temp', models.IntegerField(null=True)),
                ('total_precipitation', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('year', 'station')},
            },
        ),
        migrations.CreateModel(
            name='CornGrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('total_harvested', models.PositiveIntegerField(null=True)),
            ],
            options={
                'unique_together': {('year', 'total_harvested')},
            },
        ),
    ]
